on:
  pull_request:
  push:
    branches: [master]

jobs:

  it-tests-use-input-default-values:
    name: "IT Test - default inputs values should work fine on this repo"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Given the gh-action is used with default values
        id: test-data
        uses: ./
        with:
         command: "invalid-command-name"
         ignore-failure: true
      - uses: nick-fields/assert-action@aa0067e01f0f6545c31755d6ca128c5a3a14f6bf # v2
        name: Then outputs.status value must be 0 as the project itself makes use of pre-commit validation
        with:
          expected: 0
          actual: ${{ steps.test-data.outputs.status }}
          comparison: exact

  it-tests:
    name: "All IT Tests have to pass"
    runs-on: ubuntu-latest
    if: always()
    needs:
      # Add your tests here so that they prevent the merge of broken changes
      - it-tests-use-input-default-values
    steps:
      - uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
